version: "3"

services:
  postgresql:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "postgresql"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: permissions
